services:
  broker-service:
    build: ./broker-service
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - auth-service

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      DSN: "host=db user=postgres password=password dbname=authdb port=5432 sslmode=disable TimeZone=UTC"
    depends_on:
      - db
  
  logger-service:
    build: ./logger-service
    ports:
      - "8082:8082"
    environment:
      MONGO_URI: "mongodb://admin:password@mongo:27017/?authSource=admin"
      MONGO_DB: "logs"
    depends_on:
      - mongo
    
  mailer-service:
    build: ./mailer-service
    ports:
      - "8083:8083"
    environment:
      MAIL_HOST: "mailer"
      MAIL_DOMAIN: "localhost"
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_PORT: 1025
      MAIL_FROM_NAME: "John Doe"
      MAIL_FROM_ADDRESS: "john.doe@example.com"
      MAIL_ENCRYPTION: none
    depends_on:
      - mailer

  db:
    image: postgres:18.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27016:27017"
    volumes:
      - mongo_data:/data/db

  mailer:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP server port
      - "8025:8025" # Web UI port

volumes:
  db_data:
  mongo_data: